server:
  name: web-fe
  port: 3000

log:
  # style like: TRACE, DEBUG, INFO, WARN, ERROR
  max_level: INFO

mail:
  smtp_server: smtp.qq.com
  user_name: 549215892@qq.com
  password: jiowtgcgnuawbcae

redis:
  # redis :// [: password@] host [: port] [/ database][? [timeout=timeout[d|h|m|s|ms|us|ns]] [&database=database]]
  standalone_url: redis://:maomao@123@192.168.9.111:6379/0

mysql:
  # maomao maomao@123
  url: mysql://maomao:maomao@123@192.168.9.111:3306/test
  max_connections: 5
  min_connections: 0
  # secs
  max_lifetime: 1200
  # secs
  idle_timeout: 600
  # secs
  acquire_timeout: 30

mongodb:
  # mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
  # refer: https://www.mongodb.com/docs/manual/reference/connection-string/
  # the character of '@' in pass => %40
  standalone_url: mongodb://maomao:maomao%40123@192.168.9.111:27017/Mytest
